version: '2'

services:
  fundamental-database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${FUNDAMENTAL_DATABASE_PASSWORD}
      TZ: "Asia/Tokyo"
    ports:
      - "3314:3306"
    command: --default-authentication-plugin=mysql_native_password
  fundamental-data-server:
    build:
      context: .
      dockerfile: Dockerfile-fundamental-data-server
    ports:
     - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ${FUNDAMENTAL_DATA_SERVER_WORK_DIR}:/app
    depends_on:
      - fundamental-database
    links:
      - fundamental-database
    environment:
      FUNDAMENTAL_DATABASE_HOST: fundamental-database
      FUNDAMENTAL_DATABASE_USERNAME: ${FUNDAMENTAL_DATABASE_USERNAME}
      FUNDAMENTAL_DATABASE_PASSWORD: ${FUNDAMENTAL_DATABASE_PASSWORD}
      FUNDAMENTAL_DATA_API_APPLICATION_TOKEN: ${FUNDAMENTAL_DATA_API_APPLICATION_TOKEN}
      TZ: "Asia/Tokyo"
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SQS_ENDPOINT: ${AWS_SQS_ENDPOINT}
      UPDATE_RACER_PROFILE_QUEUE_NAME: ${UPDATE_RACER_PROFILE_QUEUE_NAME}
      SENTRY_DSN: ${FUNDAMENTAL_DATA_SERVER_SENTRY_DSN}
  official-website-crawler:
    build:
      context: .
      dockerfile: Dockerfile-official-website-crawler
    ports:
     - "3001:3001"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - ${BOATRACE_OFFICIAL_WEBSITE_CRAWLER_WORK_DIR}:/app
    links:
      - fundamental-data-server
      - official-website-proxy
      - redis
      - sqs
    environment:
      TZ: "Asia/Tokyo"
      SIDEKIQ_REDIS_URL: redis://redis:6379
      OFFICIAL_WEBSITE_PROXY_BASE_URL: http://official-website-proxy:5000
      OFFICIAL_WEBSITE_VERSION: ${OFFICIAL_WEBSITE_VERSION}
      FUNDAMENTAL_DATA_API_BASE_URL: http://fundamental-data-server:3000
      FUNDAMENTAL_DATA_API_APPLICATION_TOKEN: ${FUNDAMENTAL_DATA_API_APPLICATION_TOKEN}
      SLACK_OAUTH_ACCESS_TOKEN: ${SLACK_OAUTH_ACCESS_TOKEN}
      SENTRY_DSN: ${OFFICIAL_WEB_SITE_CRAWLER_SENTRY_DSN}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SQS_ENDPOINT: ${AWS_SQS_ENDPOINT}
      UPDATE_RACER_PROFILE_QUEUE_NAME: ${UPDATE_RACER_PROFILE_QUEUE_NAME}
  redis:
    image: redis
  official-website-proxy:
    build:
      context: .
      dockerfile: Dockerfile-official-website-proxy
    volumes:
      - ${BOATRACE_OFFICIAL_WEBSITE_PROXY_WORK_DIR}:/app
    ports:
     - "5000:5000"
    command: bash -c "pip install -r requirements.txt && python server.py"
    environment:
      TZ: "Asia/Tokyo"
  sqs:
    image: feathj/fake-sqs
    ports:
      - "9494:9494"
    environment:
      VIRTUAL_HOST: "sqs"
  teleboat-agent:
    build:
      context: .
      dockerfile: Dockerfile-teleboat-agent
    ports:
     - "3002:3002"
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3002 -b '0.0.0.0'"
    volumes:
      - ${TELEBOAT_AGENT_WORK_DIR}:/app
    environment:
      TELEBOAT_AGENT_API_APPLICATION_TOKEN: ${TELEBOAT_AGENT_API_APPLICATION_TOKEN}
      TELEBOAT_MEMBER_NUMBER: ${TELEBOAT_MEMBER_NUMBER}
      TELEBOAT_PIN: ${TELEBOAT_PIN}
      TELEBOAT_AUTHORIZATION_PASSWORD: ${TELEBOAT_AUTHORIZATION_PASSWORD}
      TELEBOAT_AUTHORIZATION_NUMBER_OF_MOBILE: ${TELEBOAT_AUTHORIZATION_NUMBER_OF_MOBILE}
      SLACK_OAUTH_ACCESS_TOKEN: ${SLACK_OAUTH_ACCESS_TOKEN}
  forcasting-database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${FORECASTING_DATABASE_PASSWORD}
      TZ: "Asia/Tokyo"
    ports:
      - "3315:3306"
    command: --default-authentication-plugin=mysql_native_password
  forecaster:
    build:
      context: .
      dockerfile: Dockerfile-forecaster
    ports:
     - "3003:3003"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3003 -b '0.0.0.0'"
    volumes:
      - ${FORECASTER_WORK_DIR}:/app
    depends_on:
      - forcasting-database
    links:
      - forcasting-database
    environment:
      FORECASTING_DATABASE_HOST: fundamental-database
      FORECASTING_DATABASE_USERNAME: ${FORECASTING_DATABASE_USERNAME}
      FORECASTING_DATABASE_PASSWORD: ${FORECASTING_DATABASE_PASSWORD}
      FORECASTING_DATA_API_APPLICATION_TOKEN: ${FORECASTING_DATA_API_APPLICATION_TOKEN}
      TZ: "Asia/Tokyo"
      SENTRY_DSN: ${FORECASTING_DATA_SERVER_SENTRY_DSN}
